### ISSUE TITLE
Upload Task fails with bad request

### ISSUE THREAD

**Issue by NanosoftDK** [Microsoft/tfs-cli#107]
When trying to upload a task to onprem TFS 2015 Update 1, the upload fails in a bad request 400.

Note that the request is running through fiddler to enable NTML auth.

**tfx-cli trace**
>C:\projects_local\tfssigntask>tfx login --auth-type basic --service-url http://tfsapp02:8080/tfs/DefaultCollection
2016-04-15T08:36:52.899Z : loader.load
TFS Cross Platform Command Line Interface v0.3.19
Copyright Microsoft Corporation
2016-04-15T08:36:53.101Z : cache.getItem
2016-04-15T08:36:53.103Z : Login.exec
> Username: asd
> Password:
2016-04-15T08:36:56.321Z : cache.setItem
2016-04-15T08:36:56.325Z : cache.setItem
Logged in successfully
>
>C:\projects_local\tfssigntask>tfx build tasks upload --task-path SignCode
2016-04-15T08:37:04.475Z : loader.load
TFS Cross Platform Command Line Interface v0.3.19
Copyright Microsoft Corporation
2016-04-15T08:37:04.775Z : cache.getItem
2016-04-15T08:37:04.777Z : cache.getItem
2016-04-15T08:37:04.780Z : Validating task json...
2016-04-15T08:37:04.781Z : Json is valid.
2016-04-15T08:37:04.878Z : Error: Failed Request: Bad Request(400) - http://tfsapp02:8080/tfs/_apis/distributedtask/tasks/6589b390-02dd-11e6-8868-2d8cec884ce0?overwrite=false
2016-04-15T08:37:04.878Z :     at processResponse (C:\Users\nni\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:60:18)
2016-04-15T08:37:04.878Z :     at C:\Users\nni\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:134:13
2016-04-15T08:37:04.878Z :     at IncomingMessage.<anonymous> (C:\Users\nni\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:39:17)
2016-04-15T08:37:04.878Z :     at IncomingMessage.emit (events.js:129:20)
2016-04-15T08:37:04.878Z :     at _stream_readable.js:908:16
2016-04-15T08:37:04.878Z :     at process._tickCallback (node.js:355:11)
Error: Failed Request: Bad Request(400) - http://tfsapp02:8080/tfs/_apis/distributedtask/tasks/6589b390-02dd-11e6-8868-2d8cec884ce0?overwrite=false

Fiddlers shows a better error message.

**Http request**
>PUT http://tfsapp02:8080/tfs/_apis/distributedtask/tasks/6589b390-02dd-11e6-8868-2d8cec884ce0?overwrite=false HTTP/1.1
Content-Type: application/octet-stream
Accept: application/json;api-version=3.0-preview.1
Host: tfsapp02:8080
User-Agent: node-TaskAgent-api
Authorization: NTLM [redacted]
X-TFS-FedAuthRedirect: Suppress
Connection: keep-alive
Content-Length: 163417

**Http response**
> HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8; api-version=3.0-preview.1
Expires: -1
Server: Microsoft-IIS/8.0
X-TFS-ProcessId: c42c816c-ea55-4589-9f85-bbca45810ac7
X-FRAME-OPTIONS: SAMEORIGIN
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 3600
Access-Control-Allow-Methods: OPTIONS,GET,POST,PATCH,PUT,DELETE
Access-Control-Expose-Headers: ActivityId,X-TFS-Session,X-MS-ContinuationToken
Access-Control-Allow-Headers: authorization
Set-Cookie: Tfs-SessionId=8fabcdb4-5103-45a1-afe7-1c37f6888a27; path=/
Set-Cookie: Tfs-SessionActive=2016-04-15T08:35:57; path=/
X-VSS-UserData: 85c602bc-d950-4309-9afe-c91edd9e7c15:nni
ActivityId: 8fabcdb4-5103-45a1-afe7-1c37f6888a27
X-TFS-Session: 8fabcdb4-5103-45a1-afe7-1c37f6888a27
X-AspNet-Version: 4.0.30319
Persistent-Auth: true
X-Powered-By: ASP.NET
P3P: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
X-Content-Type-Options: nosniff
Date: Fri, 15 Apr 2016 08:35:56 GMT
Content-Length: 53
>
>{"count":30,"value":"ContentRange header incomplete"}

**Comment by NanosoftDK** [comment]
I have discovered that in Fiddler I had enabled: Menu -> Rules -> "Remove All Encodings"
disabling that option solved to problem.

I it going to be nice when the NTLM auth works...
