### ISSUE TITLE
--overrides-file and --override doesn't work

### ISSUE THREAD

**Issue by ups216** [Microsoft/tfs-cli#136]
I'm trying to use --overrides-file to make different build for dev/production, normally there are only the baseUri and publisher id different. But when I try the following command, it doesn't work. 

tfx extension create --publisher leansoft --manifest-globs vss-extension.json --overrides-file vss-extension-abc.json

here is the error message
Could not parse contents of C:\some-extension\vss-extension-abc.json as JSON.
SyntaxError: Unexpected token ﻿

also tried --override {"baseuri":"http://localhost:1234"}

doesn't work either. 

 tfx extension create --publisher leansoft --manifest-globs vss-extension.json --override {"BaseUri":"http://localhost:12345"}
Error: Failed to parse JSON argument override. Info: SyntaxError: Unexpected token B
    at Object.parse (native)
    at ManifestJsonArgument.JsonArgument.getValue (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\arguments.js:412:35)
    at ManifestJsonArgument.Argument.initialize (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\arguments.js:84:36)
    at ManifestJsonArgument.Argument (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\arguments.js:33:14)
    at ManifestJsonArgument.JsonArgument [as constructor] (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\arguments.js:408:16)
    at new ManifestJsonArgument (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\exec\extension\default.js:21:16)
    at ExtensionCreate.TfCommand.registerCommandArgument (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\tfcommand.js:120:38)
    at ExtensionCreate.ExtensionBase.setCommandArgs (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\exec\extension\default.js:43:14)
    at ExtensionCreate.TfCommand (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\lib\tfcommand.js:29:14)
    at ExtensionCreate.ExtensionBase [as constructor] (C:\Users\leixu\AppData\Roaming\npm\node_modules\tfx-cli\_build\app\exec\extension\default.js:30:16)

**Comment by ups216** [comment]
sorry, just found out I'm using an old version. it's working fine on new version.
