### ISSUE TITLE
task upload and delete not working as i expect

### ISSUE THREAD

**Issue by mcaljamj** [Microsoft/tfs-cli#140]
I uploaded a task (IISWebAppDeployment) from the vsts-tasks repo  and it reported success. When I then listed all task it failed to show up on the list. If I try to delete it, it fails reporting "No task definition found matching id". However, if I upload a second time (without the overwrite option), that fails reporting the id and version already exist. I can turn on the --overwrite argument and it will upload a second time, but still nothing appear on the list output. 

However, if I upload a task that was shipped with the TFS 2015.3, for example the PublishBuildArtifacts task then the upload succeeds without the need for the --overwrite argument and the new version does appear in the output from "tfx build tasks list".  

This is very confusing!

TFS Cross Platform Command Line Interface v0.3.25

``C:\Users\mcaljamj>tfx build tasks upload --task-path E:\GitHub\vsts-tasks\Tasks\IISWebAppDeployment --overwrite
2016-08-17T14:05:21.708Z : loader.load
TFS Cross Platform Command Line Interface v0.3.25
Copyright Microsoft Corporation
2016-08-17T14:05:22.313Z : cache.getItem
2016-08-17T14:05:22.317Z : cache.getItem
2016-08-17T14:05:22.323Z : Validating task json...
2016-08-17T14:05:22.326Z : Json is valid.
2016-08-17T14:05:22.744Z : Success

Task at E:\GitHub\vsts-tasks\Tasks\IISWebAppDeployment uploaded successfully!

C:\Users\mcaljamj>tfx build  tasks delete --task-id 89A3A82D-4B3E-4A09-8D40-A793849DC94F
2016-08-17T14:05:50.935Z : loader.load
TFS Cross Platform Command Line Interface v0.3.25
Copyright Microsoft Corporation
2016-08-17T14:05:51.329Z : cache.getItem
2016-08-17T14:05:51.332Z : cache.getItem
2016-08-17T14:05:51.395Z : Error: Failed Request: Not Found(404) - No task definition found matching id 89a3a82d-4b3e-4a09-8d40-a793849dc94f
2016-08-17T14:05:51.395Z :     at processResponse (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:60:18)
2016-08-17T14:05:51.395Z :     at C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:148:13
2016-08-17T14:05:51.395Z :     at callback (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:135:17)
2016-08-17T14:05:51.395Z :     at handleResult (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:151:17)
2016-08-17T14:05:51.395Z :     at IncomingMessage.<anonymous> (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:162:17)
2016-08-17T14:05:51.395Z :     at emitNone (events.js:91:20)
2016-08-17T14:05:51.395Z :     at IncomingMessage.emit (events.js:185:7)
2016-08-17T14:05:51.395Z :     at endReadableNT (_stream_readable.js:975:12)
2016-08-17T14:05:51.395Z :     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-08-17T14:05:51.395Z :     at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Failed Request: Not Found(404) - No task definition found matching id 89a3a82d-4b3e-4a09-8d40-a793849dc94f

C:\Users\mcaljamj>tfx build tasks upload --task-path E:\GitHub\vsts-tasks\Tasks\IISWebAppDeployment
2016-08-17T14:06:06.019Z : loader.load
TFS Cross Platform Command Line Interface v0.3.25
Copyright Microsoft Corporation
2016-08-17T14:06:06.618Z : cache.getItem
2016-08-17T14:06:06.622Z : cache.getItem
2016-08-17T14:06:06.627Z : Validating task json...
2016-08-17T14:06:06.630Z : Json is valid.
2016-08-17T14:06:06.790Z : Error: Failed Request: Conflict(409) - A task definition with id 89a3a82d-4b3e-4a09-8d40-a793849dc94f and version 1.0.19 has already been uploaded. To replace the existing definition, re-register the task definition before uploading the package.
2016-08-17T14:06:06.790Z :     at processResponse (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:60:18)
2016-08-17T14:06:06.790Z :     at C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:134:13
2016-08-17T14:06:06.790Z :     at IncomingMessage.<anonymous> (C:\Users\mcaljamj\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.js:39:17)
2016-08-17T14:06:06.790Z :     at emitNone (events.js:91:20)
2016-08-17T14:06:06.790Z :     at IncomingMessage.emit (events.js:185:7)
2016-08-17T14:06:06.790Z :     at endReadableNT (_stream_readable.js:975:12)
2016-08-17T14:06:06.790Z :     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-08-17T14:06:06.790Z :     at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Failed Request: Conflict(409) - A task definition with id 89a3a82d-4b3e-4a09-8d40-a793849dc94f and version 1.0.19 has already been uploaded. To replace the existing definition, re-register the task definition before uploading the package.

**Comment by lucalandi** [comment]
It's also maybe related to this https://github.com/Microsoft/tfs-cli/issues/208

**Comment by bryanmacfarlane** [comment]
We don't support you uploading our in the box tasks that are not released in master.  We only support it as a patching mechanism if the product team patches it via a config change (and we ensure the version numbers interleave with one that's releasing in the rings).

tfx-cli upload was meant as a dev tool for you to upload tasks you develop (inner loop development).
