### ISSUE TITLE
Unable to login with 0.4.1 (with vso-node-api 6.1.2-preview, old RESTClient) 

### ISSUE THREAD

**Issue by grawcho** [Microsoft/tfs-cli#199]
trying to login to both on premise and VSTS i get an error from wrong API call to vso-node-api RestClient:

<root-folder>\tfx-cli\node_modules\vso-node-api\RestClient.js:252
        onResult(null, res.statusCode, jsonObj);
        ^

TypeError: onResult is not a function
    at _processResponse (<root-folder>\tfx-cli\node_modules\vso-node-api\RestClient.js:252:9)
    at httpClient.get (<root-folder>\tfx-cli\node_modules\vso-node-api\RestClient.js:176:13)
    at callback (<root-folder>\tfx-cli\node_modules\vso-node-api\HttpClient.js:280:17)
    at handleResult (<root-folder>\tfx-cli\node_modules\vso-node-api\HttpClient.js:298:17)
    at IncomingMessage.res.on (<root-folder>\tfx-cli\node_modules\vso-node-api\HttpClient.js:309:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by devedse** [comment]
I'm seeing the same error when calling tfx login -u https://.....visualstudio.com/DefaultCollection -t .........

I installed the latest version of tfx using:
npm install -g tfx-cli

**Comment by trevorsg** [comment]
Thanks! Investigating...

**Comment by grawcho** [comment]
resolved after roll back.
