### ISSUE TITLE
Overrides File error

### ISSUE THREAD

**Issue by MrTarantula** [Microsoft/tfs-cli#213]
Override files aren't working for me. Here is the command I am using:

`C:\TFSExtension>tfx extension create --manifests vss-extension.json --overrides-file config/dev.json`

Here is the trace:

```
2017-05-03T17:05:12.702Z : loader.load
TFS Cross Platform Command Line Interface v0.4.5
Copyright Microsoft Corporation
2017-05-03T17:05:13.073Z : Error: Could not parse contents of C:\TFSExtension\config\dev.json as JSON.
2017-05-03T17:05:13.073Z :
2017-05-03T17:05:13.073Z :     at C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\_build\exec\extension\default.js:101:27
2017-05-03T17:05:13.073Z :     at _fulfilled (C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:854:54)
2017-05-03T17:05:13.073Z :     at self.promiseDispatch.done (C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:883:30)
2017-05-03T17:05:13.073Z :     at Promise.promise.promiseDispatch (C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:816:13)
2017-05-03T17:05:13.073Z :     at C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:624:44
2017-05-03T17:05:13.073Z :     at runSingle (C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:137:13)
2017-05-03T17:05:13.073Z :     at flush (C:\Users\me\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\q\q.js:125:13)
2017-05-03T17:05:13.073Z :     at _combinedTickCallback (internal/process/next_tick.js:73:7)
2017-05-03T17:05:13.073Z :     at process._tickCallback (internal/process/next_tick.js:104:9)
error: Error: Could not parse contents of C:\TFSExtension\config\dev.json as JSON.
error:
```

Contents of the `dev.json` file:

```
{
     "baseUri": "http://localhost:52265"
}
```

**Comment by ILMTitan** [comment]
See if your file has a byte order mark.
I was having similar problems. I was using the Powershell Out-File cmdlet, which creates a file with the byte order mark. Node.js does not like the byte order mark.

**Comment by MrTarantula** [comment]
That may have been it. I haven't tried it since switching to the ALM Rangers yo template, which required me to copy/paste most of my files. I just tried and it `--overrides-file` works. I don't have a way of verifying BOM was the issue, but it could have been.

**Comment by dengyakui** [comment]
Same problem, wast me 20 minutes to found the issue.   New file on windows has BOM character default.
tfs-cli should add some clear err msg when it  see the BOM.
