### ISSUE TITLE
Failing to upload task on TFS 2017.1

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/tfs-cli#216]
Since the upgrade of TFS 2017 to Update 1, tfs-cli is not able to upload the build tasks to TFS.

```
C:\Users\majcicam\Source\Repos\TFS Build tasks>tfx build tasks upload --task-pat
h ./XLDeploy
2017-05-30T11:03:13.838Z : loader.load
TFS Cross Platform Command Line Interface v0.4.7
Copyright Microsoft Corporation
2017-05-30T11:03:14.431Z : cache.getItem
2017-05-30T11:03:14.431Z : cache.getItem
2017-05-30T11:03:14.447Z : Validating task json...
2017-05-30T11:03:14.447Z : Json is valid.
2017-05-30T11:03:14.681Z : Error: Failed Request: Not Found(404) -
2017-05-30T11:03:14.681Z :     at processResponse (C:\Users\majcicam\AppData\Roa
ming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:59:18)
2017-05-30T11:03:14.681Z :     at C:\Users\majcicam\AppData\Roaming\npm\node_mod
ules\tfx-cli\node_modules\vso-node-api\RestClient.js:133:13
2017-05-30T11:03:14.681Z :     at IncomingMessage.<anonymous> (C:\Users\majcicam
\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\HttpClient.j
s:39:17)
2017-05-30T11:03:14.681Z :     at emitNone (events.js:91:20)
2017-05-30T11:03:14.681Z :     at IncomingMessage.emit (events.js:185:7)
2017-05-30T11:03:14.681Z :     at endReadableNT (_stream_readable.js:974:12)
2017-05-30T11:03:14.681Z :     at _combinedTickCallback (internal/process/next_t
ick.js:80:11)
2017-05-30T11:03:14.681Z :     at process._tickCallback (internal/process/next_t
ick.js:104:9)
error: Error: Failed Request: Not Found(404) -

C:\Users\majcicam\Source\Repos\TFS Build tasks>
```

This seems to be due to the fact that now the resource used to do that (_apis/distributedtask/tasks/) is moved on per collection basis and is not anymore on the server. If I try to upload it via my custom PS script and I do prefix above mentioned resource with the Collection name, the upload succeeds.

**Comment by dpurge** [comment]
Same problem here. Can you provide a workaround while we are waiting for the permanent fix?

**Comment by mmajcica** [comment]
@dpurge you need to provide as service url during the login the path pointing towards the collection, ex. https://yourTFSurl:port/DefaultCollection
Seems that with the 2017.1 tasks became collection level items and now it is required to pass in the collection name as service url.

**Comment by dpurge** [comment]
Yes, I've found too that it works if I add collection name to the url.
I've just got back to add a comment to this issue about it. Thank you for your response :-)
