### ISSUE TITLE
error: Error: write ECONNRESET when calling tasks upload

### ISSUE THREAD

**Issue by tgillitzer** [Microsoft/tfs-cli#250]
I get the following when trying to run tasks upload.

tfx build tasks upload --task-path ./Task --trace-level debug
TFS Cross Platform Command Line Interface v0.5.3
Copyright Microsoft Corporation
2018-01-11T19:55:18.364Z : cache.getItem
2018-01-11T19:55:18.372Z : Validating task json...
2018-01-11T19:55:18.376Z : Json is valid.
2018-01-11T19:55:20.887Z : Error: write ECONNRESET
2018-01-11T19:55:20.887Z :     at exports._errnoException (util.js:1018:11)
2018-01-11T19:55:20.887Z :     at WriteWrap.afterWrite (net.js:800:14)
error: Error: write ECONNRESET

tasks list works fine.

I'm running TFS 2017.1 (15.112.26307.0).   I've done this in the past, but not since we upgraded to 2017.   I am using a PAT to authenticate.   I can't seem to get basic auth to work, I haven't checked to see if it still enabled on the TFS side.   I switched to the PAT instead of messing with it.

**Comment by tgillitzer** [comment]
I got basic auth re-enabled and still have the same problem.   The tasks list command works fine though.
