### ISSUE TITLE
 TypeError: Cannot read property 'versions' of null

### ISSUE THREAD

**Issue by adelwin** [microsoft/tfs-cli#337]
Getting the above error when trying to publish an extension that I created.

Full stack trace below:
```
/tmp $ ./scripts/320-tfx-extension-publish.sh
TFX - Publish
TFS Cross Platform Command Line Interface v0.7.11
Copyright Microsoft Corporation
2020-01-27T08:12:30.874Z : Publishing /tmp/test-decorator.vsix
Checking if this extension is already published
2020-01-27T08:12:30.885Z : Read vsix as zip... Size (bytes): 1951
2020-01-27T08:12:30.904Z : Files in the zip: [Content_Types].xml, extension.vsomanifest, manifests/, manifests/decorator-post-job-clean.yaml, manifests/decorator-pre-job-init.yaml, extension.vsixmanifest
It isn't, create a new extension.

== Extension Validation In Progress ==
This should take only a few seconds, but in some cases may take a bit longer. You can choose to exit (Ctrl-C) if you don't want to wait. To get the validation status, you may run the command below. If you don't want TFX to wait for validation, use the --no-wait-validation parameter. This extension will be available after validation is successful.

tfx extension isvalid --publisher jenkins-test-publisher --extension-id test-decorator --version 0.0.1 --service-url https://marketplace.visualstudio.com/ --token <your PAT>
2020-01-27T08:12:45.545Z : TypeError: Cannot read property 'versions' of null
2020-01-27T08:12:45.545Z :     at /usr/lib/node_modules/tfx-cli/_build/exec/extension/_lib/publish.js:406:40
2020-01-27T08:12:45.545Z :     at processTicksAndRejections (internal/process/task_queues.js:94:5)
error: TypeError: Cannot read property 'versions' of null
```

I'm not sure what `versions` property that I did not set.
I was able to previously publish the same extension, (PS: i'm actually publishing not as version 0.0.1, i had to redact that)

I tried updating the tfx-cli using `npm i --global tfx-cli` still with the same result.

**Comment by adelwin** [comment]
nevermind, got it... i missed a step, i suppressed the output of the previous step. That step was to create a publisher.

I guess good to have a good error message then?

**Comment by robertlyson** [comment]
Just encountered the same issue, it would be great to have a better error message as @adelwin suggested. 

Keep up with the great work you have done so far 👍

**Comment by ceakarsu** [comment]
I was having the same problem with version 0.7.x. Then I downgraded to v0.6.4 and it actually gave me the correct error message which is 

**Not Found(404) - The requested publisher doesn't exist**

Once I created the publisher with an account that has vso.manage permission, this error went away.

**Comment by anatolybolshakov** [comment]
Hi everyone, thanks for reporting! Leaving this for error message improvement.
