### ISSUE TITLE
Build task - Timeout on upload

### ISSUE THREAD

**Issue by felpel** [microsoft/tfs-cli#338]
Hi,

I'm trying to upload a custom task in Azure DevOps with the following commands and it times out after 5 minutes on the upload. I'm using the latest version of `tfx-cli` with Node's LTS (12.x).

1. Login:
```bash
npx tfx-cli login --auth-type pat --token {patToken} --service-url https://dev.azure.com/{myOrg} --no-prompt --no-color --trace-level debug
```
2. Upload task:
```
npx tfx-cli build tasks upload --task-path ./ --no-prompt --no-color --trace-level debug
```

Commands output:
```bash
2020-04-01T23:18:49.9727937Z npx: installed 217 in 5.866s
2020-04-01T23:18:50.2512096Z TFS Cross Platform Command Line Interface v0.7.11
2020-04-01T23:18:50.2512470Z Copyright Microsoft Corporation
2020-04-01T23:18:50.2539765Z 2020-04-01T23:18:50.246Z : Login.exec
2020-04-01T23:18:50.3407393Z 2020-04-01T23:18:50.333Z : cache.setItem
2020-04-01T23:18:50.3419396Z 2020-04-01T23:18:50.334Z : cache.setItem
2020-04-01T23:18:50.3427996Z Logged in successfully
2020-04-01T23:18:58.4777580Z npx: installed 217 in 5.941s
2020-04-01T23:18:58.8546981Z TFS Cross Platform Command Line Interface v0.7.11
2020-04-01T23:18:58.8547715Z Copyright Microsoft Corporation
2020-04-01T23:18:58.8559460Z 2020-04-01T23:18:58.841Z : cache.getItem
2020-04-01T23:18:58.8576508Z 2020-04-01T23:18:58.843Z : cache.getItem
2020-04-01T23:18:58.8610060Z 2020-04-01T23:18:58.846Z : Validating task json...
2020-04-01T23:18:58.8620818Z 2020-04-01T23:18:58.847Z : Json is valid.
2020-04-01T23:18:58.8645705Z Collection URL: https://dev.azure.com/{myOrg}
2020-04-01T23:22:46.4569746Z 2020-04-01T23:22:46.453Z : Error: Request timeout: /{myOrg}/_apis/distributedtask/tasks/{taskId}
2020-04-01T23:22:46.4570554Z 2020-04-01T23:22:46.453Z :     at ClientRequest.<anonymous> (C:\Users\ContainerAdministrator\AppData\Roaming\npm-cache\_npx\21884\node_modules\tfx-cli\node_modules\typed-rest-client\HttpClient.js:276:26)
2020-04-01T23:22:46.4571144Z 2020-04-01T23:22:46.453Z :     at Object.onceWrapper (events.js:427:28)
2020-04-01T23:22:46.4573169Z 2020-04-01T23:22:46.453Z :     at ClientRequest.emit (events.js:321:20)
2020-04-01T23:22:46.4573583Z error: Error: Request timeout: /{myOrg}/_apis/distributedtask/tasks/{taskId}
2020-04-01T23:22:46.4573997Z 2020-04-01T23:22:46.453Z :     at TLSSocket.emitRequestTimeout (_http_client.js:714:9)
2020-04-01T23:22:46.4574399Z 2020-04-01T23:22:46.453Z :     at Object.onceWrapper (events.js:427:28)
2020-04-01T23:22:46.4574968Z 2020-04-01T23:22:46.453Z :     at TLSSocket.emit (events.js:321:20)
2020-04-01T23:22:46.4575326Z 2020-04-01T23:22:46.453Z :     at TLSSocket.Socket._onTimeout (net.js:478:8)
2020-04-01T23:22:46.4575688Z 2020-04-01T23:22:46.453Z :     at listOnTimeout (internal/timers.js:549:17)
2020-04-01T23:22:46.4576013Z 2020-04-01T23:22:46.453Z :     at processTimers (internal/timers.js:492:7)
2020-04-01T23:22:48.4845652Z ##[error]Cmd.exe exited with code '-1'.
2020-04-01T23:22:48.5212678Z ##[section]Finishing: Run 
```

**Comment by felpel** [comment]
It seems that GitHub might have experienced a major outage when I was trying to upload a new version for my task, by looking at the [status page](https://githubstatus.com). 

Closing this issue.
