### ISSUE TITLE
Cannot read property 'value' of null

### ISSUE THREAD

**Issue by stevetsang** [Microsoft/tfs-cli#46]
When trying to list or upload a task I get the following error message:
```
steven-imac:Tasks Steven$ tfx build tasks list
Copyright Microsoft Corporation

unhandled:
TypeError: Cannot read property 'value' of null
    at /usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/VsoClient.js:101:60
    at processResponse (/usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/RestClient.js:56:9)
    at /usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/RestClient.js:164:13
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/HttpClient.js:120:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```
The message isn't clear so I am unsure what is causing this.

I have logged in successfully with tfx and have tried this on both windows and mac where these messages are coming out

Here is the same command with trace turned on:
```
steven-imac:Tasks Steven$ tfx build tasks list
2015-10-15T17:39:29.197Z : loader.load
2015-10-15T17:39:29.199Z : build-list.js
2015-10-15T17:39:29.199Z : build-queue.js
2015-10-15T17:39:29.199Z : build-show.js
2015-10-15T17:39:29.199Z : build-tasks-create.js
2015-10-15T17:39:29.199Z : build-tasks-delete.js
2015-10-15T17:39:29.199Z : build-tasks-list.js
2015-10-15T17:39:29.199Z : build-tasks-upload.js
2015-10-15T17:39:29.199Z : build-tasks.js
2015-10-15T17:39:29.200Z : build.js
2015-10-15T17:39:29.200Z : help.js
2015-10-15T17:39:29.200Z : login.js
2015-10-15T17:39:29.200Z : parse.js
2015-10-15T17:39:29.200Z : resources
2015-10-15T17:39:29.200Z : version.js
2015-10-15T17:39:29.200Z : loader.match
2015-10-15T17:39:29.200Z : Command matched
2015-10-15T17:39:29.200Z : No command matched
2015-10-15T17:39:29.202Z : loaded /usr/local/lib/node_modules/tfx-cli/exec/build-tasks-list.js
Copyright Microsoft Corporation

2015-10-15T17:39:29.202Z : loader.getCollectionUrl
2015-10-15T17:39:29.202Z : loader.getCachedUrl
2015-10-15T17:39:29.207Z : Retrieved collection url from cache
2015-10-15T17:39:29.207Z : url: http://tfs:8080/tfs
2015-10-15T17:39:29.207Z : inputs.check
2015-10-15T17:39:29.207Z : auth.getCredentials
2015-10-15T17:39:29.208Z : auth.getCachedCredentials
2015-10-15T17:39:29.208Z : Retrieved credentials from cache
2015-10-15T17:39:29.209Z : Using basic creds
2015-10-15T17:39:29.211Z : build-tasks-list.exec
2015-10-15T17:39:29.211Z : Initializing agent API...
2015-10-15T17:39:29.211Z : tfcommand.checkArguments
2015-10-15T17:39:29.211Z : inputs.check
2015-10-15T17:39:29.212Z : Searching for build tasks...
unhandled:
TypeError: Cannot read property 'value' of null
    at /usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/VsoClient.js:101:60
    at processResponse (/usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/RestClient.js:56:9)
    at /usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/RestClient.js:164:13
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/tfx-cli/node_modules/vso-node-api/HttpClient.js:120:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by bryanmacfarlane** [comment]
Did it ever work?
Have you done this?  https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md

**Comment by ericsciple** [comment]
From your log:
2015-10-15T17:39:29.207Z : Retrieved collection url from cache
2015-10-15T17:39:29.207Z : url: http://tfs:8080/tfs

Try "tfx login" again make sure you specified the collection URL, not the server URL. You'll need to specify "tfx login --authtype basic" if you're connecting to an on-premise instance.

**Comment by stevetsang** [comment]
I have use "tfx login --authtype basic" and it said it logged in fine but as @ericsciple posted I didn't used the collection url which I will try.

Thanks to both!

**Comment by ericsciple** [comment]
I repro'd this as well. The error message is not great: "Cannot read property 'value' of null". It worked properly when I used the collection url.

Thanks for letting us know. I wonder if there's a reliable way the tool can detect this case better - ideally on login if collection url is indeed required for all of the subcommands. I'm not sure if any of the commands work with the server url, so it might be the case that login should still succeed but the subcommands error out gracefully. I'll fwd along to someone who will know. Thanks again.

**Comment by stevetsang** [comment]
Yeah it works now thanks to both!
