### ISSUE TITLE
The CLI doesn't allow entering friendly name

### ISSUE THREAD

**Issue by tarunaroraonline** [Microsoft/tfs-cli#47]
Using latest version of the CLI and trying to create a new build task. 

When entering the short name for the task, the CLI skips the friendly name, then complains the friendly name is missing.

**Comment by scottdallamura** [comment]
This is a known issue with node 4.x. One workaround is to use 0.12.7.

-----Original Message-----

**Comment by tarunaroraonline** [comment]
Thank you works in Node 0.12.7.

**Comment by tarunaroraonline** [comment]
The build task upload fails in this version though... 

PS C:\Users\Tarun> tfx build tasks upload .\MyTask
Copyright Microsoft Corporation

unhandled:
TypeError: Cannot read property 'value' of null
    at C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\VsoClient.js:101:60
    at processResponse (C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:
56:9)
    at C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:164:13
    at IncomingMessage.<anonymous> (C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\Ht
tpClient.js:120:17)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

I am getting the following error when querying for the list of build tasks too...

PS C:\Users\Tarun> tfx build tasks list
Copyright Microsoft Corporation

unhandled:
TypeError: Cannot read property 'value' of null
    at C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\VsoClient.js:101:60
    at processResponse (C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:
56:9)
    at C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\RestClient.js:164:13
    at IncomingMessage.<anonymous> (C:\Users\Tarun\AppData\Roaming\npm\node_modules\tfx-cli\node_modules\vso-node-api\Ht
tpClient.js:120:17)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by tarunaroraonline** [comment]
Uninstall and reinstall did the trick, version 0.12 works fine, however still fails in version 4 with the error message on friendly name not specified.

**Comment by bryanmacfarlane** [comment]
This should be fixed/worked around with latest client pushed (0.3.x)
