### ISSUE TITLE
Cannot run tfx with node 0.1.0

### ISSUE THREAD

**Issue by grawcho** [Microsoft/tfs-cli#73]
on fedora 23 nodejs stable is 0.1.0 when installing tfx-cli according to Readme instructions i get 
an error that lead me to find that i need node 0.1.2 - after installation everything worked OK.
Please add this to the docs.

2016-02-10T13:22:12.526Z : TypeError: Object #<Object> has no method 'parse'
2016-02-10T13:22:12.526Z :     at /usr/lib/node_modules/tfx-cli/_build/app/lib/command.js:42:35
2016-02-10T13:22:12.526Z :     at Array.forEach (native)
2016-02-10T13:22:12.526Z :     at /usr/lib/node_modules/tfx-cli/_build/app/lib/command.js:37:15
2016-02-10T13:22:12.526Z :     at _fulfilled (/usr/lib/node_modules/tfx-cli/node_modules/q/q.js:834:54)
2016-02-10T13:22:12.526Z :     at self.promiseDispatch.done (/usr/lib/node_modules/tfx-cli/node_modules/q/q.js:863:30)
2016-02-10T13:22:12.526Z :     at Promise.promise.promiseDispatch (/usr/lib/node_modules/tfx-cli/node_modules/q/q.js:796:13)
2016-02-10T13:22:12.526Z :     at /usr/lib/node_modules/tfx-cli/node_modules/q/q.js:604:44
2016-02-10T13:22:12.526Z :     at runSingle (/usr/lib/node_modules/tfx-cli/node_modules/q/q.js:137:13)
2016-02-10T13:22:12.526Z :     at flush (/usr/lib/node_modules/tfx-cli/node_modules/q/q.js:125:13)
2016-02-10T13:22:12.526Z :     at process._tickCallback (node.js:442:13)
TypeError: Object #<Object> has no method 'parse'

**Comment by trevorsg** [comment]
Thanks. I updated the README.
